export enum ExpenseCategory {
  TRAVEL = 'TRAVEL',
  ACCOMMODATION = 'ACCOMMODATION',
  MEAL = 'MEAL',
  TRANSPORT = 'TRANSPORT',
  OFFICE_SUPPLIES = 'OFFICE_SUPPLIES',
  COMMUNICATION = 'COMMUNICATION',
  OTHER = 'OTHER',
}
